import openai
import os
import logging
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")

# Set up logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
handler = logging.FileHandler('openai_service.log')
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)


def generate_chatgpt_response(prompt, model="gpt-4"):
    """
    Generate a response from OpenAI's GPT-4 given a specific prompt.

    Args:
    - prompt (str): The prompt to pass to OpenAI.
    - model (str): The OpenAI model to use (default: 'gpt-4').

    Returns:
    - str: The response generated by OpenAI.
    """
    try:
        logger.info("Generating response from OpenAI for given prompt.")
        response = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are an academic advisor bot."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.5,
            max_tokens=1500
        )
        return response.choices[0].message['content'].strip()
    except Exception as e:
        logger.error(f"Error while generating OpenAI response: {str(e)}")
        return f"An error occurred while generating a response: {str(e)}"


def extract_text_from_image(image_content):
    """
    Use GPT-4 Vision to extract text from an image.

    Args:
    - image_content (binary): The image content to analyze.

    Returns:
    - str: Extracted text from the image.
    """
    try:
        logger.info("Extracting text from image using GPT-4 Vision.")
        response = openai.Image.create(model="dalle-vision", image=image_content)
        return response['data']['text'].strip()
    except Exception as e:
        logger.error(f"Error during image analysis: {str(e)}")
        return f"An error occurred during image analysis: {str(e)}"
